server:
  port: 10010
spring:
  application:
    name: mongo-demo
  data:
    mongodb:
      # 配置多个ip集群 mongodb://用户名:密码@ip:port,ip:port,ip:port/数据库
      uri: mongodb://root:example@10.10.10.19:27017/admin